### ISSUE TITLE
(Windows) [vite] Internal server error: Missing "./dist/vue.js" export in "@islands/hydration" package, after run of `npm run dev`

### ISSUE THREAD

**Issue by mrauhu** [ElMassimo/iles#185]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

On Windows run of the `npm run dev` command will produce errors:

<details>

<summary>[vite] Internal server error: Missing "./dist/vue.js" export in "@islands/hydration" package</summary>

```
      at bail (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:33612:8)
      at resolve (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:33689:10)
      at resolveExports (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:34675:12)
      at resolveDeepImport (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:34693:31)
      at tryNodeResolve (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:34410:20)
      at Context.resolveId (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:34147:32)
      at Object.resolveId (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:35469:55)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.resolve (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:35234:23)
      at async Object.resolveId (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:35469:32)
```
</details>

<details>
<summary>[vite] Internal server error: Missing "./dist/hydration.js" export in "@islands/hydration" package</summary>

```
      at bail (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:33612:8)
      at resolve (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:33689:10)
      at resolveExports (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:34675:12)
      at resolveDeepImport (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:34693:31)
      at tryNodeResolve (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:34410:20)
      at Context.resolveId (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:34147:32)
      at Object.resolveId (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:35469:55)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.resolve (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:35234:23)
      at async Object.resolveId (file:///C:/Projects/iles-app/node_modules/vite/dist/node/chunks/dep-74663fff.js:35469:32)
```
</details>

Similar to #161, maybe the `file://` prefix is also needed for running the `dev` script on Windows.

### Reproduction 🐞

On Windows:

```
npm init iles@latest
cd iles-app
npm i
npm run dev
```

<details>
<summary>Dependencies Info</summary>

_Run `npx iles info` and `pnpm list` (or `npm list`) and provide the output:_

```
iles v0.8.3 vite v3.0.8
```
```
iles-app@0.0.0 C:\Projects\iles-app
+-- iles@0.8.3
+-- typescript@4.7.4
`-- vue-tsc@0.38.9
```

</details>

### Screenshots 📷

![image](https://user-images.githubusercontent.com/2821574/184990297-de3b61c2-8a60-4460-a8fd-bea0a7dd9588.png)

**Comment by ElMassimo** [comment]
Hi, thanks for the report!

Seems unusual that this wasn't reported earlier if it's related to paths, since the users from #161 would have detected it?

Which package manager are you using?

**Comment by mrauhu** [comment]
> Which package manager are you using?

@ElMassimo NPM.

```
npm -v
8.5.5

node -v
v16.15.0
```

**Comment by ohuu** [comment]
I'm also seeing this problem. It occurs when adding an interactive component with any of the `client:*` directives. The reason I didn't report it was because until now the site I'm building is 100% statically generated. 

Interestingly I've deployed and it seems to work in production, this looks like a problem in dev only.

My bet is that we're missing a `file://` somewhere like @mrauhu suggested. @ElMassimo if you need me to post you anything let me know. In the mean time here is the error I'm seeing my end:

![image](https://user-images.githubusercontent.com/25370730/185955715-7136e7f9-d5b1-490b-85e4-8aa39a8d2493.png)

**Comment by ElMassimo** [comment]
Thanks for reporting!

Fixed in [`@islands/hydration` `v0.8.1`](https://github.com/ElMassimo/iles/commit/56cbd457df11c64298cd5fb6ee99226a116ed128).

**Comment by ohuu** [comment]
I've just upgraded to 0.8.4 and I'm still seeing this problem. I suggest we reopen this issue.

**Comment by ElMassimo** [comment]
@ohuu Can you open a new issue with information about your `iles.config.ts` and related plugins?

I tested `0.8.4` in Windows and it's starting the dev server correctly, so I'll need more information to debug it.

**Comment by ohuu** [comment]
My bad. Turns out yarn doesn't automatically upgrade indirect dependencies, so I was still on `@islands/hydration@0.8.0`. `0.8.1` does indeed fix the issue. Sorry for the noise
